### ISSUE TITLE
Asynchronous interactor

### ISSUE THREAD

**Issue by stepanhruda** [lausobo/clean-architecture#1]
What puzzles me a bit is the block assignment to the asynchronous interactor response. I know this is a weird edge case, but it could happen that `[interactor loginWithUsername:@"foo"]` finishes before `response.onCompletion` gets assigned, so it never gets called.

**Comment by lausobo** [comment]
In the setter `onCompletion`, it'd also check if the job is done, then it
will execute the completion block right away.

2013/2/4 Stepan Hruda notifications@github.com

> What puzzles me a bit is the block assignment to the asynchronous
> interactor response. I know this is a weird edge case, but it could happen
> that [interactor loginWithUsername:@"foo"] finishes before
> response.onCompletion gets assigned, so it never gets called.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/luisobo/clean-architecture/issues/1.

## 

_LinkedIn:_ http://es.linkedin.com/in/luissolano/en

**Comment by stepanhruda** [comment]
Totally missed that one. Nice. I think this might be a reason to actually use a thin superclass for interactors that handles this kind of stuff.

**Comment by lausobo** [comment]
Absolutely

El lunes, 4 de febrero de 2013, Stepan Hruda escribió:

> Totally missed that one. Nice. I think this might be a reason to actually
> use a thin superclass for interactors that handles this kind of stuff.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/luisobo/clean-architecture/issues/1#issuecomment-13089004.

## 

_LinkedIn:_ http://es.linkedin.com/in/luissolano/en
